services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL={DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: