FROM python:3.9-slim-buster
ENV PYTHONDONTWRITEBYTECODE=1 \
 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt .
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 build-essential=12.6 \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m appuser && \
 chown -R appuser:appuser /app
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]